//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPizzeria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRecord
    {
        public int RecordID { get; set; }
        public string MealName { get; set; }
        public int Amount { get; set; }
        public int OrderID { get; set; }
    }
}
